# ==============================================================================
# Environment
# ==============================================================================
from os import path as path


data_dir = path.join("..", "..", "data")
res_dir = path.join("..", "..", "results")

# ==============================================================================
# Meta Rules
# ==============================================================================
rule all_dscore_dist:
	input:
	    path.join(res_dir, "papers.dscore.density.png"),
	    path.join(res_dir, "papers.dscore-absolute.density.png"),
	    path.join(res_dir, "papers.dscore.ecdf.png"),


# ==============================================================================
# Rules
# ==============================================================================
rule plot_dscore:
	input:
	    path.join(data_dir, "Paperid_Year_Discipline_Teamsize_Distance_Dscore.txt"),
	output:
	    path.join(res_dir, "papers.dscore.density.png"),
	    path.join(res_dir, "papers.dscore-absolute.density.png"),
	    path.join(res_dir, "papers.dscore.ecdf.png"),
	script:
		"plot_dist.R"

