# ==============================================================================
# Environment
# ==============================================================================
from os import path as path

data_dir = path.join("..", "..", "data")
res_dir = path.join("..", "..", "results")


# ==============================================================================
# Meta Rules
# ==============================================================================
rule all_author_interactions:
	input:


# ==============================================================================
# Rules
# ==============================================================================
rule analyze_interactions:
	input:
	    path.join(data_dir, 'Paperid_Remoteness_Authors_Teamroles.csv'),
 		path.join(data_dir, 'Paperid_Year_TeamSize_AuthorCitationCumulative.txt'),
	script:
		"count_team_roles.py"

