# ==============================================================================
# Environment
# ==============================================================================
from os import path as path


data_dir = path.join("..", "..", "data")
res_dir = path.join("..", "..", "results")

# ==============================================================================
# Meta Rules
# ==============================================================================
rule all_examples:
	input:
	    path.join(res_dir, "dag.png"),
	    path.join(res_dir, "berksons-paradox.png"),


# ==============================================================================
# Rules
# ==============================================================================
rule plot_causal_graph:
	output:
	    path.join(res_dir, "dag.png"),
	script:
		"plot_graphs.R"

rule plot_berksons_paradox:
	output:
	    path.join(res_dir, "berksons-paradox.png"),
	script:
		"plot_example_dist.R"

